# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bcfe381213618088e45f097488b41dbde35dfb057f11f8fb4fcca55ccab2aed2dc0e49bb60f35ab3e426789ed9e9a265fa1f671d57a94a07ce37669d9e6afecf

test:
  secret_key_base: 8384da84214a29bbf7ef08426b3ab83a418f674a96176273e00f27724190c5a2724a36c8c621acabf69d11c54300cd33c316349dc9f7a0324d0d16629ccf818f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
