# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 11) do

  create_table "addresses", :force => true do |t|
    t.column "user_id",           :integer,                :null => false
    t.column "delegation_tag_id", :integer,                :null => false
    t.column "email",             :string,   :limit => 60
    t.column "tel1",              :string,   :limit => 30
    t.column "tel2",              :string,   :limit => 30
    t.column "memo",              :string
    t.column "skype",             :string
    t.column "mixi",              :string
    t.column "twitter",           :string
    t.column "created_at",        :datetime
    t.column "updated_at",        :datetime
  end

  add_index "addresses", ["user_id", "delegation_tag_id"], :name => "index_addresses_on_user_id_and_delegation_tag_id"

  create_table "commands", :force => true do |t|
    t.column "user_id",       :integer,                                :null => false
    t.column "task_id",       :integer
    t.column "tag_id",        :integer
    t.column "project_id",    :integer
    t.column "type",          :string,   :limit => 30, :default => "", :null => false
    t.column "done_at",       :datetime
    t.column "params",        :text
    t.column "data_for_undo", :text
  end

  add_index "commands", ["user_id"], :name => "index_commands_on_user_id"

  create_table "memos", :force => true do |t|
    t.column "user_id",         :integer, :null => false
    t.column "memo_tagging_id", :integer, :null => false
    t.column "memo",            :text
  end

  add_index "memos", ["user_id", "memo_tagging_id"], :name => "index_memos_on_user_id_and_memo_tagging_id"

  create_table "private_keys", :force => true do |t|
    t.column "user_id",       :integer,                               :null => false
    t.column "export_tag_id", :integer,                               :null => false
    t.column "key",           :string,  :limit => 32, :default => "", :null => false
  end

  add_index "private_keys", ["user_id", "export_tag_id"], :name => "index_private_keys_on_user_id_and_export_tag_id"
  add_index "private_keys", ["key"], :name => "index_private_keys_on_key"

  create_table "projects", :force => true do |t|
    t.column "user_id",           :integer,                  :null => false
    t.column "parent_project_id", :integer
    t.column "name",              :string,   :default => "", :null => false
    t.column "goal",              :string
    t.column "review_interval",   :integer,  :default => 0,  :null => false
    t.column "created_at",        :datetime
    t.column "updated_at",        :datetime
    t.column "reviewed_at",       :datetime
    t.column "next_review",       :datetime
    t.column "locked",            :boolean
  end

  add_index "projects", ["user_id"], :name => "index_projects_on_user_id"
  add_index "projects", ["user_id", "parent_project_id"], :name => "index_projects_on_user_id_and_parent_project_id"

  create_table "schedules", :force => true do |t|
    t.column "user_id",             :integer,                 :null => false
    t.column "schedule_tagging_id", :integer,                 :null => false
    t.column "date",                :date
    t.column "from",                :datetime
    t.column "to",                  :datetime
    t.column "preparation",         :integer,  :default => 0, :null => false
    t.column "place",               :string
    t.column "memo",                :string
    t.column "created_at",          :datetime
    t.column "updated_at",          :datetime
  end

  add_index "schedules", ["user_id", "schedule_tagging_id"], :name => "index_schedules_on_user_id_and_schedule_tagging_id"

  create_table "sessions", :force => true do |t|
    t.column "session_id", :string
    t.column "data",       :text
    t.column "updated_at", :datetime
  end

  add_index "sessions", ["session_id"], :name => "index_sessions_on_session_id"
  add_index "sessions", ["updated_at"], :name => "index_sessions_on_updated_at"

  create_table "taggings", :force => true do |t|
    t.column "user_id", :integer,                               :null => false
    t.column "task_id", :integer,                               :null => false
    t.column "tag_id",  :integer,                               :null => false
    t.column "type",    :string,  :limit => 30, :default => "", :null => false
  end

  add_index "taggings", ["user_id", "tag_id"], :name => "index_taggings_on_user_id_and_tag_id"
  add_index "taggings", ["task_id"], :name => "index_taggings_on_task_id"

  create_table "tags", :force => true do |t|
    t.column "user_id", :integer,                                :null => false
    t.column "name",    :string,  :limit => 100, :default => "", :null => false
    t.column "type",    :string,  :limit => 30,  :default => "", :null => false
  end

  add_index "tags", ["user_id"], :name => "index_tags_on_user_id"

  create_table "tasks", :force => true do |t|
    t.column "user_id",    :integer,                  :null => false
    t.column "project_id", :integer,                  :null => false
    t.column "text",       :string,   :default => "", :null => false
    t.column "url",        :string
    t.column "status",     :integer,  :default => 0,  :null => false
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
    t.column "done_at",    :datetime
    t.column "trashed_at", :datetime
  end

  add_index "tasks", ["user_id"], :name => "index_tasks_on_user_id"
  add_index "tasks", ["user_id", "project_id"], :name => "index_tasks_on_user_id_and_project_id"

  create_table "users", :force => true do |t|
    t.column "login",         :string,   :limit => 80, :default => "", :null => false
    t.column "email",         :string,   :limit => 60, :default => "", :null => false
    t.column "firstname",     :string,   :limit => 40
    t.column "lastname",      :string,   :limit => 40
    t.column "password_salt", :string
    t.column "password_hash", :string
    t.column "created_at",    :datetime
    t.column "updated_at",    :datetime
  end

end
