# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 3) do

  create_table "addresses", :force => true do |t|
    t.column "name",       :string,   :limit => 20, :default => "", :null => false
    t.column "zipCode",    :string,   :limit => 7
    t.column "address",    :string,   :limit => 80, :default => "", :null => false
    t.column "created_on", :datetime,                               :null => false
    t.column "updated_on", :datetime,                               :null => false
  end

  create_table "mails", :force => true do |t|
    t.column "mailAddress", :string,  :limit => 80, :default => "", :null => false
    t.column "address_id",  :integer,                               :null => false
  end

  create_table "user_details", :force => true do |t|
    t.column "profile",    :text,                  :default => "", :null => false
    t.column "telNum",     :string,  :limit => 14
    t.column "address_id", :integer,                               :null => false
  end

end
