# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 2) do

  create_table "transcripts", :force => true do |t|
    t.column "title",        :string,   :limit => 100, :default => "", :null => false
    t.column "filename",     :string
    t.column "file",         :binary
    t.column "content_type", :string,                  :default => "", :null => false
    t.column "description",  :text
    t.column "tag",          :string,   :limit => 100
    t.column "user_id",      :string,   :limit => 80,  :default => "", :null => false
    t.column "created_on",   :datetime,                                :null => false
    t.column "updated_on",   :datetime,                                :null => false
  end

end
