# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 21) do

  create_table "attachments", :force => true do |t|
    t.column "parent_id",    :integer
    t.column "content_type", :string
    t.column "filename",     :string
    t.column "thumbnail",    :string
    t.column "size",         :integer
    t.column "width",        :integer
    t.column "height",       :integer
  end

  create_table "page_autosaves", :force => true do |t|
    t.column "page_id",    :integer
    t.column "created_at", :datetime
    t.column "content",    :string
    t.column "user_id",    :integer
  end

  create_table "page_versions", :force => true do |t|
    t.column "page_id",    :integer
    t.column "version",    :integer
    t.column "name",       :string
    t.column "wiki_id",    :integer
    t.column "content",    :text
    t.column "updated_at", :datetime
    t.column "path",       :string
    t.column "user_id",    :integer
  end

  create_table "pages", :force => true do |t|
    t.column "name",    :string
    t.column "wiki_id", :integer
    t.column "content", :text
    t.column "version", :integer
    t.column "path",    :string
    t.column "user_id", :integer
  end

  create_table "permissions", :id => false, :force => true do |t|
    t.column "user_id", :integer
    t.column "wiki_id", :integer
  end

  create_table "plans", :force => true do |t|
    t.column "name",        :string
    t.column "monthly_fee", :integer
  end

  create_table "users", :force => true do |t|
    t.column "email",      :string
    t.column "password",   :string
    t.column "verified",   :boolean,  :default => false
    t.column "name",       :string
    t.column "created_at", :datetime
  end

  create_table "wikis", :force => true do |t|
    t.column "name",            :string
    t.column "email",           :string
    t.column "password",        :string
    t.column "public_password", :string
    t.column "domain",          :string
    t.column "plan_id",         :integer
    t.column "user_id",         :integer
    t.column "anyone_write",    :boolean, :default => true
    t.column "anyone_read",     :boolean, :default => true
    t.column "css",             :text
    t.column "classes",         :text
    t.column "header",          :text
    t.column "footer",          :text
  end

end
