# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 3) do

  create_table "transcripts", :force => true do |t|
    t.column "title",        :string,   :limit => 100, :default => "", :null => false
    t.column "filename",     :string
    t.column "file",         :binary
    t.column "content_type", :string,                  :default => "", :null => false
    t.column "description",  :text
    t.column "tag",          :string,   :limit => 100
    t.column "user_id",      :string,   :limit => 80,  :default => "", :null => false
    t.column "created_on",   :datetime,                                :null => false
    t.column "updated_on",   :datetime,                                :null => false
  end

  create_table "users", :force => true do |t|
    t.column "login",           :string,   :limit => 80, :default => "", :null => false
    t.column "salted_password", :string,   :limit => 40, :default => "", :null => false
    t.column "email",           :string,   :limit => 60, :default => "", :null => false
    t.column "firstname",       :string,   :limit => 40
    t.column "lastname",        :string,   :limit => 40
    t.column "salt",            :string,   :limit => 40, :default => "", :null => false
    t.column "verified",        :integer,                :default => 0
    t.column "role",            :string,   :limit => 40
    t.column "security_token",  :string,   :limit => 40
    t.column "token_expiry",    :datetime
    t.column "created_at",      :datetime
    t.column "updated_at",      :datetime
    t.column "logged_in_at",    :datetime
    t.column "deleted",         :integer,                :default => 0
    t.column "delete_after",    :datetime
  end

end
